openapi: 3.0.3
info:
  title: Stock Analytics Backend API
  version: 0.1.0
  description: API for PSX fundamental analytics platform
servers:
  - url: http://localhost:4000
    description: Local backend
paths:
  /api/health:
    get:
      summary: Health check
      operationId: getHealth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: ok
        service:
          type: string
          example: backend
        timestamp:
          type: string
          format: date-time

