openapi: 3.0.3
info:
  title: Stock Analytics Backend API
  version: 0.1.0
  description: API for PSX fundamental analytics platform
servers:
  - url: http://localhost:4000
    description: Local backend
paths:
  /api/health:
    get:
      summary: Health check
      operationId: getHealth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  
  /api/dashboard/sectors:
    get:
      summary: Get sector breakdown data
      operationId: getSectorBreakdown
      responses:
        '200':
          description: Sector breakdown data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SectorBreakdownResponse'
  
  /api/companies:
    get:
      summary: Get companies list
      operationId: getCompanies
      parameters:
        - name: sector
          in: query
          description: Filter by sector
          schema:
            type: string
        - name: status
          in: query
          description: Listing status filter (e.g., NC)
          schema:
            type: string
        - name: page
          in: query
          description: Page number (1-based)
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: Limit number of results
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: List of companies
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompaniesResponse'
  
  /api/companies/{symbol}:
    get:
      summary: Get company analytics
      operationId: getCompanyAnalytics
      parameters:
        - name: symbol
          in: path
          required: true
          description: Company symbol
          schema:
            type: string
      responses:
        '200':
          description: Company analytics data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyAnalyticsResponse'

  /api/indices/{code}:
    get:
      summary: Get index snapshot by code
      operationId: getIndexSnapshot
      parameters:
        - name: code
          in: path
          required: true
          description: Index code (e.g., KSE100)
          schema:
            type: string
      responses:
        '200':
          description: Index snapshot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndexSnapshot'

  /api/market/performers:
    get:
      summary: Get market performers (gainers, losers, volume leaders)
      operationId: getMarketPerformers
      parameters:
        - name: board
          in: query
          description: Market board code
          schema:
            type: string
        - name: session
          in: query
          description: Trading session identifier
          schema:
            type: string
        - name: assetClass
          in: query
          description: Asset class filter
          schema:
            type: string
            enum: [equity, debt]
      responses:
        '200':
          description: Market performers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerformersResponse'

  /api/market/watch:
    get:
      summary: Get market watch table
      operationId: getMarketWatch
      responses:
        '200':
          description: Market watch rows
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketWatchResponse'

  /api/market/summary:
    get:
      summary: Get today's market boards summary
      operationId: getMarketSummary
      responses:
        '200':
          description: Boards totals summary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MarketSummaryResponse'

  /api/historical:
    post:
      summary: Get historical OHLCV series
      operationId: getHistoricalSeries
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HistoricalRequest'
      responses:
        '200':
          description: Historical OHLCV series
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoricalSeriesResponse'

  /api/announcements:
    post:
      summary: Get company announcements
      operationId: getAnnouncements
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnnouncementsRequest'
      responses:
        '200':
          description: Announcements list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnnouncementsResponse'

  /api/company/{symbol}/reports:
    get:
      summary: Get company reports (documents)
      operationId: getCompanyReports
      parameters:
        - name: symbol
          in: path
          required: true
          description: Company symbol
          schema:
            type: string
      responses:
        '200':
          description: Reports list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompanyReportsResponse'

  /api/company/{symbol}/intraday:
    get:
      summary: Get intraday price series for a company
      operationId: getCompanyIntraday
      parameters:
        - name: symbol
          in: path
          required: true
          description: Company symbol
          schema:
            type: string
      responses:
        '200':
          description: Intraday series
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IntradaySeriesResponse'

  /api/indices:
    get:
      summary: Get snapshots for all indices
      operationId: getIndices
      responses:
        '200':
          description: Indices snapshot list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IndicesResponse'

  /api/indices/{code}/intraday:
    get:
      summary: Get intraday series for an index
      operationId: getIndexIntraday
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Intraday series
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IntradaySeriesResponse'

  /api/symbols:
    get:
      summary: Get all tradable symbols
      operationId: getSymbols
      responses:
        '200':
          description: Symbols list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SymbolsResponse'
components:
  schemas:
    HealthResponse:
      type: object
      properties:
        status:
          type: string
          example: ok
        service:
          type: string
          example: backend
        timestamp:
          type: string
          format: date-time
    
    SectorBreakdownResponse:
      type: object
      properties:
        sectors:
          type: array
          items:
            $ref: '#/components/schemas/SectorData'
        totalMarketCap:
          type: number
          description: Total market cap in PKR millions
        lastUpdated:
          type: string
          format: date-time
    
    SectorData:
      type: object
      properties:
        name:
          type: string
          example: Banking
        marketCap:
          type: number
          description: Market cap in PKR millions
        percentage:
          type: number
          description: Percentage of total market
        companiesCount:
          type: integer
          description: Number of companies in sector
        avgPE:
          type: number
          description: Average P/E ratio
        performance1M:
          type: number
          description: 1-month performance percentage
    
    CompaniesResponse:
      type: object
      properties:
        companies:
          type: array
          items:
            $ref: '#/components/schemas/CompanyBasic'
        total:
          type: integer
        page:
          type: integer
        limit:
          type: integer
    
    CompanyBasic:
      type: object
      properties:
        symbol:
          type: string
          example: HBL
        name:
          type: string
          example: Habib Bank Limited
        sector:
          type: string
          example: Banking
        marketCap:
          type: number
          description: Market cap in PKR millions
        price:
          type: number
          description: Current share price
        change:
          type: number
          description: Price change percentage
        pe:
          type: number
          description: P/E ratio
    
    CompanyAnalyticsResponse:
      type: object
      properties:
        company:
          $ref: '#/components/schemas/CompanyDetails'
        financials:
          $ref: '#/components/schemas/CompanyFinancials'
        ratios:
          $ref: '#/components/schemas/CompanyRatios'
        performance:
          $ref: '#/components/schemas/CompanyPerformance'
    
    CompanyDetails:
      type: object
      properties:
        symbol:
          type: string
        name:
          type: string
        sector:
          type: string
        industry:
          type: string
        marketCap:
          type: number
        sharesOutstanding:
          type: number
        description:
          type: string
        website:
          type: string
    
    CompanyFinancials:
      type: object
      properties:
        revenue:
          type: number
          description: TTM revenue in PKR millions
        netIncome:
          type: number
          description: TTM net income in PKR millions
        totalAssets:
          type: number
          description: Total assets in PKR millions
        totalEquity:
          type: number
          description: Total equity in PKR millions
        cash:
          type: number
          description: Cash and equivalents in PKR millions
        debt:
          type: number
          description: Total debt in PKR millions
    
    CompanyRatios:
      type: object
      properties:
        pe:
          type: number
          description: P/E ratio
        pb:
          type: number
          description: P/B ratio
        roe:
          type: number
          description: Return on equity percentage
        roa:
          type: number
          description: Return on assets percentage
        debtToEquity:
          type: number
          description: Debt to equity ratio
        currentRatio:
          type: number
          description: Current ratio
        grossMargin:
          type: number
          description: Gross margin percentage
        netMargin:
          type: number
          description: Net margin percentage
    
    CompanyPerformance:
      type: object
      properties:
        price:
          type: number
          description: Current price
        change1D:
          type: number
          description: 1-day change percentage
        change1W:
          type: number
          description: 1-week change percentage
        change1M:
          type: number
          description: 1-month change percentage
        change3M:
          type: number
          description: 3-month change percentage
        change1Y:
          type: number
          description: 1-year change percentage
        high52W:
          type: number
          description: 52-week high
        low52W:
          type: number
          description: 52-week low

    IndicesResponse:
      type: object
      properties:
        asOf:
          type: string
          format: date-time
        indices:
          type: array
          items:
            $ref: '#/components/schemas/IndexSnapshot'

    IndexSnapshot:
      type: object
      properties:
        code:
          type: string
        name:
          type: string
        value:
          type: number
        change:
          type: number
        changePct:
          type: number
        high:
          type: number
        low:
          type: number
        volume:
          type: number
        asOf:
          type: string
          format: date-time

    Performer:
      type: object
      properties:
        symbol:
          type: string
        name:
          type: string
        price:
          type: number
        changePct:
          type: number
        volume:
          type: number

    PerformersResponse:
      type: object
      properties:
        gainers:
          type: array
          items:
            $ref: '#/components/schemas/Performer'
        losers:
          type: array
          items:
            $ref: '#/components/schemas/Performer'
        volumeLeaders:
          type: array
          items:
            $ref: '#/components/schemas/Performer'

    MarketWatchRow:
      type: object
      properties:
        symbol:
          type: string
        sector:
          type: string
        listedIn:
          type: string
          description: Comma separated index memberships
        ldcp:
          type: number
        open:
          type: number
        high:
          type: number
        low:
          type: number
        current:
          type: number
        change:
          type: number
        percentChange:
          type: number
        volume:
          type: integer

    MarketWatchResponse:
      type: object
      properties:
        rows:
          type: array
          items:
            $ref: '#/components/schemas/MarketWatchRow'

    BoardSummary:
      type: object
      properties:
        board:
          type: string
        trades:
          type: integer
        volume:
          type: integer
        value:
          type: number

    MarketSummaryResponse:
      type: object
      properties:
        asOf:
          type: string
          format: date-time
        boards:
          type: array
          items:
            $ref: '#/components/schemas/BoardSummary'

    HistoricalRequest:
      type: object
      required: [symbol, dateFrom, dateTo, interval]
      properties:
        symbol:
          type: string
        dateFrom:
          type: string
          format: date
        dateTo:
          type: string
          format: date
        interval:
          type: string
          enum: [daily, weekly, monthly, intraday]

    OHLCVPoint:
      type: object
      properties:
        date:
          type: string
          description: ISO date or datetime
        open:
          type: number
        high:
          type: number
        low:
          type: number
        close:
          type: number
        volume:
          type: integer

    HistoricalSeriesResponse:
      type: object
      properties:
        symbol:
          type: string
        series:
          type: array
          items:
            $ref: '#/components/schemas/OHLCVPoint'

    AnnouncementsRequest:
      type: object
      required: [symbol]
      properties:
        symbol:
          type: string
        fromDate:
          type: string
          format: date
        toDate:
          type: string
          format: date
        categories:
          type: array
          items:
            type: string

    AnnouncementItem:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
          format: date
        title:
          type: string
        category:
          type: string
        url:
          type: string

    AnnouncementsResponse:
      type: object
      properties:
        symbol:
          type: string
        announcements:
          type: array
          items:
            $ref: '#/components/schemas/AnnouncementItem'

    CompanyReportItem:
      type: object
      properties:
        date:
          type: string
          format: date
        title:
          type: string
        category:
          type: string
        pdfUrl:
          type: string

    CompanyReportsResponse:
      type: object
      properties:
        symbol:
          type: string
        reports:
          type: array
          items:
            $ref: '#/components/schemas/CompanyReportItem'

    IntradayPoint:
      type: object
      properties:
        time:
          type: string
          description: ISO datetime
        price:
          type: number
        volume:
          type: integer

    IntradaySeriesResponse:
      type: object
      properties:
        symbol:
          type: string
        points:
          type: array
          items:
            $ref: '#/components/schemas/IntradayPoint'

    SymbolItem:
      type: object
      properties:
        symbol:
          type: string
        name:
          type: string
        sectorName:
          type: string
        isETF:
          type: boolean
        isDebt:
          type: boolean

    SymbolsResponse:
      type: object
      properties:
        symbols:
          type: array
          items:
            $ref: '#/components/schemas/SymbolItem'

