// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type ChartDataPoint struct {
	Timestamp string  `json:"timestamp"`
	Value     float64 `json:"value"`
	Volume    float64 `json:"volume"`
}

type GetSectorCompaniesRequest struct {
	SectorId string `path:"sectorId"`
	Limit    int    `form:"limit,optional,default=10"`
	SortBy   string `form:"sort_by,optional,default=market_cap"`
}

type GetSectorDetailsRequest struct {
	SectorId  string `path:"sectorId"`
	Timeframe string `form:"timeframe,optional,default=1M"`
}

type GetSectorsRequest struct {
	Timeframe string `form:"timeframe,optional,default=1D"`
	SortBy    string `form:"sort_by,optional,default=market_cap"`
	SortOrder string `form:"sort_order,optional,default=desc"`
}

type HealthResponse struct {
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
	Version   string `json:"version"`
}

type MarketSummary struct {
	TotalMarketCap      float64 `json:"total_market_cap"`
	Kse100Index         float64 `json:"kse100_index"`
	Kse100Change        float64 `json:"kse100_change"`
	TotalVolume         float64 `json:"total_volume"`
	TotalTurnover       float64 `json:"total_turnover"`
	AdvanceDeclineRatio float64 `json:"advance_decline_ratio"`
	LastUpdated         string  `json:"last_updated"`
}

type PerformanceChart struct {
	Timeframe  string           `json:"timeframe"`
	DataPoints []ChartDataPoint `json:"data_points"`
}

type PerformanceMetrics struct {
	CurrentChange float64 `json:"current_change"`
	OneWeek       float64 `json:"one_week"`
	OneMonth      float64 `json:"one_month"`
	ThreeMonths   float64 `json:"three_months"`
	SixMonths     float64 `json:"six_months"`
	OneYear       float64 `json:"one_year"`
	Ytd           float64 `json:"ytd"`
}

type SectorCompaniesResponse struct {
	SectorId   string          `json:"sector_id"`
	SectorName string          `json:"sector_name"`
	Companies  []SectorCompany `json:"companies"`
	TotalCount int             `json:"total_count"`
}

type SectorCompany struct {
	Symbol              string  `json:"symbol"`
	Name                string  `json:"name"`
	MarketCap           float64 `json:"market_cap"`
	MarketCapPercentage float64 `json:"market_cap_percentage"`
	CurrentPrice        float64 `json:"current_price"`
	ChangePercent       float64 `json:"change_percent"`
	Volume              float64 `json:"volume"`
	PeRatio             float64 `json:"pe_ratio"`
	PbRatio             float64 `json:"pb_ratio"`
}

type SectorCompareRequest struct {
	SectorIds []string `json:"sector_ids"`
	Timeframe string   `json:"timeframe,optional,default=1M"`
	Metrics   []string `json:"metrics,optional"`
}

type SectorCompareResponse struct {
	Comparison  []SectorOverview `json:"comparison"`
	Timeframe   string           `json:"timeframe"`
	GeneratedAt string           `json:"generated_at"`
}

type SectorDetail struct {
	Id                  string             `json:"id"`
	Name                string             `json:"name"`
	Description         string             `json:"description"`
	MarketCap           float64            `json:"market_cap"`
	MarketCapPercentage float64            `json:"market_cap_percentage"`
	CompanyCount        int                `json:"company_count"`
	Performance         PerformanceMetrics `json:"performance"`
	VolumeToday         float64            `json:"volume_today"`
	TurnoverToday       float64            `json:"turnover_today"`
	Volatility          float64            `json:"volatility"`
	Beta                float64            `json:"beta"`
	LastUpdated         string             `json:"last_updated"`
}

type SectorDetailResponse struct {
	Sector           SectorDetail           `json:"sector"`
	PerformanceChart PerformanceChart       `json:"performance_chart"`
	FinancialMetrics SectorFinancialMetrics `json:"financial_metrics"`
	VolumeMetrics    VolumeMetrics          `json:"volume_metrics"`
	Companies        []SectorCompany        `json:"companies"`
}

type SectorFinancialMetrics struct {
	AvgPeRatio       float64 `json:"avg_pe_ratio"`
	AvgPbRatio       float64 `json:"avg_pb_ratio"`
	AvgDividendYield float64 `json:"avg_dividend_yield"`
	AvgRoe           float64 `json:"avg_roe"`
	AvgDebtToEquity  float64 `json:"avg_debt_to_equity"`
	MedianMarketCap  float64 `json:"median_market_cap"`
}

type SectorOverview struct {
	Id                  string             `json:"id"`
	Name                string             `json:"name"`
	MarketCap           float64            `json:"market_cap"`
	MarketCapPercentage float64            `json:"market_cap_percentage"`
	Performance         PerformanceMetrics `json:"performance"`
	CompanyCount        int                `json:"company_count"`
	VolumeToday         float64            `json:"volume_today"`
	TurnoverToday       float64            `json:"turnover_today"`
	TopCompanies        []TopCompany       `json:"top_companies"`
}

type SectorsOverviewResponse struct {
	Sectors       []SectorOverview `json:"sectors"`
	MarketSummary MarketSummary    `json:"market_summary"`
	LastUpdated   string           `json:"last_updated"`
}

type TopCompany struct {
	Symbol        string  `json:"symbol"`
	Name          string  `json:"name"`
	MarketCap     float64 `json:"market_cap"`
	CurrentPrice  float64 `json:"current_price"`
	ChangePercent float64 `json:"change_percent"`
}

type VolumeMetrics struct {
	TodayVolume    float64 `json:"today_volume"`
	AvgVolume30d   float64 `json:"avg_volume_30d"`
	TodayTurnover  float64 `json:"today_turnover"`
	AvgTurnover30d float64 `json:"avg_turnover_30d"`
}
