// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package handler

import (
	"net/http"

	health "sector-service/internal/handler/health"
	sector "sector-service/internal/handler/sector"
	"sector-service/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Health check endpoint
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.HealthCheckHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// Get all PSX sectors overview
				Method:  http.MethodGet,
				Path:    "/sectors",
				Handler: sector.GetAllSectorsHandler(serverCtx),
			},
			{
				// Get detailed sector analysis
				Method:  http.MethodGet,
				Path:    "/sectors/:sectorId",
				Handler: sector.GetSectorDetailsHandler(serverCtx),
			},
			{
				// Get top companies in sector
				Method:  http.MethodGet,
				Path:    "/sectors/:sectorId/companies",
				Handler: sector.GetSectorCompaniesHandler(serverCtx),
			},
			{
				// Compare multiple sectors
				Method:  http.MethodPost,
				Path:    "/sectors/compare",
				Handler: sector.CompareSectorsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
